name: Run all tests & checks

on:
  push:
    branches: [ main, nightly ]
  pull_request:
    branches: [ main, nightly ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Upgrade pip
        run: python -m pip install --upgrade pip setuptools==44.0.0

      - name: Install development dependencies
        run: make dev-requirements

      - name: Static code analysis
        run: make test-lint

      # Enable when types annotations are fixed
      # - name: Static type checks
      #   run: make test-types

      - name: Code formatting
        run: make test-format

      - name: Package tests
        run: make test-pythonpackage

      # Enable step when test-install.sh is implemented
      # - name: Plugin installation & rendering checks
      #   run: make test-install
